const questions = [
  {
    question: "Thủ đô của Pháp là gì?",
    A: "Berlin",
    B: "Madrid",
    C: "Rome",
    D: "Paris",
    correct: "D",
  },
  {
    question: "Ai là tác giả của tác phẩm 'Truyện Kiều'?",
    A: "Nguyễn Du",
    B: "Nguyễn Trãi",
    C: "Hồ Xuân Hương",
    D: "Phan Bội Châu",
    correct: "A",
  },
  {
    question: "Năm 1969, con người lần đầu tiên đặt chân lên đâu?",
    A: "Sao Hỏa",
    B: "Mặt Trăng",
    C: "Sao Kim",
    D: "Sao Thủy",
    correct: "B",
  },
  {
    question: "Chất nào sau đây là kim loại?",
    A: "Heli",
    B: "Oxy",
    C: "Sắt",
    D: "Clo",
    correct: "C",
  },
  {
    question: "Ai là người sáng lập ra hãng Microsoft?",
    A: "Steve Jobs",
    B: "Mark Zuckerberg",
    C: "Bill Gates",
    D: "Larry Page",
    correct: "C",
  },
  {
    question: "Bức tranh 'Mona Lisa' do ai vẽ?",
    A: "Vincent van Gogh",
    B: "Pablo Picasso",
    C: "Leonardo da Vinci",
    D: "Claude Monet",
    correct: "C",
  },
  {
    question: "Phim 'Avatar' do đạo diễn nào thực hiện?",
    A: "Steven Spielberg",
    B: "Christopher Nolan",
    C: "James Cameron",
    D: "Martin Scorsese",
    correct: "C",
  },
  {
    question: "Nguyên tố nào có ký hiệu hóa học là O?",
    A: "Vàng",
    B: "Oxy",
    C: "Bạc",
    D: "Đồng",
    correct: "B",
  },
  {
    question: "Vị tổng thống thứ 16 của Hoa Kỳ là ai?",
    A: "George Washington",
    B: "Abraham Lincoln",
    C: "Thomas Jefferson",
    D: "Theodore Roosevelt",
    correct: "B",
  },
  {
    question: "Trong tin học, 'CPU' là viết tắt của từ gì?",
    A: "Central Process Unit",
    B: "Central Processing Unit",
    C: "Central Programming Unit",
    D: "Central Power Unit",
    correct: "B",
  },
];

export default questions;
